export const icons = {
  // 'Shell': '#',
  // 'TeX': '#',
  // 'R': '#',
  // 'Smarty': '#',
  // 'Jupyter Notebook': '#',
  'Vim script': 'vim',
  'Ruby': 'ruby',
  'HTML': 'html5',
  'CSS': 'css3',
  'JavaScript': 'javascript',
  'Vue': 'vuejs',
  'CoffeeScript': 'coffeescript',
  'Java': 'java',
  'TypeScript': 'typescript',
  'Python': 'python',
  'C++': 'cplusplus',
  'C': 'c',
  'C#': 'csharp',
  'PHP': 'php',
  'Go': 'go',
  'Swift': 'swift',
  'Dockerfile': 'docker',
  'AppleScript': 'apple',
}
